// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetIpInfoService(arg1) {
  return window['go']['main']['App']['GetIpInfoService'](arg1);
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function StartAPIService() {
  return window['go']['main']['App']['StartAPIService']();
}

export function StopAPIService() {
  return window['go']['main']['App']['StopAPIService']();
}
