// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetIpInfoService(arg1:string):Promise<string>;

export function Greet(arg1:string):Promise<string>;

export function StartAPIService():Promise<void>;

export function StopAPIService():Promise<void>;
